[project]
name = "swmaps"
version = "0.1.0"
dependencies = [
    "dask",
    "earthengine-api",
    "numpy",
    "pandas",
    "rasterio",
    "geopandas",
    "shapely",
    "xarray",
    "scikit-learn",
    "tqdm",
    "xgboost",
]

[tool.setuptools]
packages = ["swmaps"]
