# -------------------------
# Imagery date range
# -------------------------

start_date = "2020-01-01"
end_date = "2021-12-31"

# -------------------------
# General Settings & Mission / sensor
# -------------------------

cloud_filter  = 30
out_dir = "data/outputs/quickstart_train"
skip_download = false
clear_outputs = true

mission = ["sentinel-2"]

# -------------------------
# Location of interest
# -------------------------

geometry = "data/regions/somerset_train.geojson"

# -------------------------
# Validation Set
# -------------------------

do_val = true
val_start_date = "1999-04-01"
val_end_date   = "2000-04-10"
val_date_step = 120
val_region = "data/regions/somerset_val.geojson"
val_dir       = "data/outputs/quickstart_train/validation"
val_cdl_out = "data/outputs/quickstart_train/cdl/val_cdl_2019.tif"

# -------------------------
# CDL labels download
# -------------------------

download_cdl = true
cdl_year = 2019
cdl_region = ["data/regions/somerset_train.geojson", "data/regions/somerset_val.geojson"]

# -------------------------
# Segmentation Traing
# -------------------------

segmentation_model = "farseg"
epochs = 10
batch_size = 8
learning_rate = 1e-4
loss = "dice"
segmentation_weights = "pretrained"

# -------------------------
# Segmentation Traing
# -------------------------

run_segmentation = true
segmentation_out_dir = "data/outputs/quickstart_train/segmentation"
save_png = true
